logging:
  level: INFO
  loggers:
    com.photosharesite: DEBUG

mediaFilesBucketName: kieran-finn-pss-media-files-bljd #todo: pass this in through terraform

database:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: photosharesite-user #todo: pass this in through terraform

  # the password
  password: G3XMXh5wNbTsCqdO #todo: pass this in through terraform

  # the JDBC URL
  url: jdbc:mysql://3.254.54.19:3306/photosharesite #todo: pass this in through terraform

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    noAccessToProcedureBodies: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute